---
version: '3.8'
services:
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        env_file:
            - ../.env
        environment:
            - GF_INSTALL_PLUGINS=cognitedata-datasource
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana.ini:/etc/grafana/grafana.ini
volumes:
    grafana_data: {}
